#!/bin/bash
# this program is copyleft
#
# the comments are in english language and spanish language
#
# english: create to system variables:
# spanish: crea a las variables del sistema:
for a in mifirewall mivariable ruta yes no fprogram fver web tenue brillo normal ; do declare -x  $a ; done ;
# english: create to system variables, firewall config:
# spanish: crea a las variables del sistema, configuracion del firewall:
for a in hayvpn vpn logservertcp redserver redcliente servidortcp servidorudp clienteudp clientetcp ; do declare -x  $a ; done ;
# english: create to system variables, script configuration for rules:
# spanish: crea a las variables del sistema, configuracion del scrript para reglas::
for a in activaservidor activacliente mojado ; do declare -x $a ; done ;
######
######
###################### basic system variables:
###################### las basicas variables del sistema:
mifirewall=$1; mivariable=$2
ruta="/usr/sbin";
yes=""; no="echo off" ;
fprogram="Fran iptables" ; fver="1.26" ;
web="https://sourceforge.net/projects/f-iptables/files/latest/download" ;
tenue="tput dim"; brillo="tput bold"; normal="tput sgr0" ;
###################### english: user variables to modify with $yes or $no
###################### spanish: variables de usuario para modificar con $yes o $no
hayvpn="$no"; #  hayvpn: $yes to allow exceptional host and $no to drop exceptional host
# spanish: hayvpn: $yes para permitir hosts excepcionales y $no para evitar permitirlos
hayping="$no"; #  hayping: $yes to allow pings to others and $no to drop pings to others
# spanish: hayping: $yes para permitir hacer ping a otros y $no para evitar permitirlo
haylogserver="$no"; # haylogserver: $yes to tcp log and $no to do not log tcp
# spanish: haylogserver: $yes para logear tcp y $no para no logear tcp
######################	english: User variables to modify add with "," and join ranges with ":"
######################  spanish: Variables de usuario para añadir con "," y poner rangos con ":"
vpn="baldras.wesnoth.org,wesnoth.org"; # vpn: to allow a host excepcitonal without firewall
# spanish: vpn: host excepcionales que saltan el firewall
logservertcp=ssh,ftp-data,ftp; # logservertcp:  the tcp ports to log
#logservertcp: los puertos tcp para logear
redserver=0/0; # redserver: the net to server
# spanish: redserver: la red cual servidor
redcliente=0/0; #  redcliente: the net to client
# spanish: redcliente  la red cual cliente
servidortcp=discard; #  servidortcp: tcp ports to server
# spanish: servidortcp: puertos tcp para servir
servidorudp=discard; #  servidorudp: udp ports to server
# spanish: servidorudp: puertos udp para servir
clienteudp=domain,domain-s,ntp,bootpc,bootps; # clienteudp: udp ports to client
# spanish: clienteudp: puertos udp para ser cliente
clientetcp=domain,domain-s,http,https; #  clientetcp: tcp ports to client
# spanish: clientetcp: puertos tcp para ser cliente
##############################		english: End from user variables file, overwriter initial values       |||||
##############################          spanish: Fin de archivo de variables, sobre escribe valores iniciales  !!!!!
##
##
##
##
##
##
##
##
##############################       english: are you root (uid 0) ?
##############################       spanish: eres admnistrador (identificador 0) ?
if [ "$(id -u)" = "0" ]; then echo -n;
else  echo "  ####################### f-iptables need to be root to work" ; echo ;
echo "  the $fprogram version $fver "
echo "  ##########################################"
echo
echo "  ####################### The iptables help: "
echo ""
echo "  The First Option  (To configure iptables):  reconfig or offline or client or server or allpermisive or eraserules"
echo "  The First Option        (To show sockets):  list or iproute or sockets"
echo "  The Second option              (Optional):  configs in folder /etc/f-iptables/ : " $(ls /etc/f-iptables/)
echo "  For Example"
echo "                              (Example 1):  launch:  $0 list                 /to list iptables rules"
echo "                              (Example 2):  launch:  $0 client web1.cfg      /to config iptables like client web"
echo "                              (Example 3):  launch:  $0 lonhelp              /to show long help from $fprogram"
echo ""
echo "  Notes: $fprogram version $fver Wich only works with the ports selected in ipv4 in the config file choosed, blocking ipv6"
echo; echo; exit ; fi
##############################       english: create the default1.cfg file when it do not exists and the files1.cfg
##############################       spanish: crea el archivo default1.cfg cuando no existe, y los archivos1.cfg
if [ -d /etc/f-iptables ]; then echo -n ; else rm /etc/f-iptables; mkdir /etc/f-iptables ; fi
if [ -f /etc/f-iptables/default1.cfg ]; then echo -n ;
else cat $0 | head -55 > /etc/f-iptables/default1.cfg; fi
if [ -f /etc/f-iptables/web1.cfg ]; then echo -n ;
else echo "clienteudp=domain,domain-s,ntp,bootpc,bootps; clientetcp=domain,domain-s,http,https;" > /etc/f-iptables/web1.cfg; fi
if [ -f /etc/f-iptables/games1.cfg ]; then echo -n ;
else echo "clienteudp=domain,domain-s,ntp,bootpc,bootps,14000:44000; clientetcp=domain,domain-s,http,https,14998:15002;"  > /etc/f-iptables/games1.cfg; fi
if [ -f /etc/f-iptables/server1.cfg ]; then echo -n ;
else echo "clienteudp=domain,domain-s,ntp,bootpc,bootps; clientetcp=domain,domain-s,http,https; haylogserver=; logservertcp=ssh; servidortcp=ssh,http,https;" > /etc/f-iptables/server1.cfg; fi
if [ -f /etc/f-iptables/vpn1.cfg ]; then echo -n ;
else echo "clienteudp=domain,domain-s,ntp,bootpc,bootps; clientetcp=domain,domain-s,http,https;  hayvpn=; vpn=baldras.wesnoth.org,wesnoth.org;" > /etc/f-iptables/vpn1.cfg ; fi
###############################       english: overwrite system varibles for files variables configured
###############################       spanish: sobreescribe las variables por la de los archivos de configuracion
if [ -f /etc/f-iptables/$2 ]; then source /etc/f-iptables/$2 ; else source /etc/f-iptables/default1.cfg; fi
#############################        english: system script, the first options
#############################        spanish: script the sistema, primeras opciones
if [ "$mifirewall" = "offline" ]; then echo FIREWALL OFFLINE;
activarservidor="$no" activarcliente="$no" mojado="$no";
elif [ "$mifirewall" = "client" ];then echo FIREWALL CLIENT;
activarservidor="$no" activarcliente="" mojado="$no";
elif [ "$mifirewall" = "server" ]; then echo FIREWALL CLIENT AND SERVER;
activarservidor=""  activarcliente="" mojado="$no";
elif [ "$mifirewall" = "allpermisive" ]; then echo FIREWALL ALLPERMISIVE;
activarservidor="$no" activarcliente="$no" mojado="";
elif [ "$mifirewall" = "iproute" ]; then $brillo ; echo ; echo "   $fprogram version $fver" ;
echo "   ##############################################"
echo; ip route ls; echo; echo "   Notes: route socket in  Fran iptables version $fver "; echo; exit
elif [ "$mifirewall" = "sockets" ]; then $brillo;  echo;
echo; $brillo; echo "     SOCKETS LIST : THE $fprogram $fver FIREWALL configure IPV4 AND blocking TO IPV6"; $normal ;
echo "  ########################################################################################"
echo; echo "     THE IPV6 SOCKETS:" ; ss -a6 ; echo ;  echo "     THE IPV4 SOCKETS:" ; ss -a4 ;
echo; echo "Notes: socket list in $fprogram version $fver "; exit
elif [ "$mifirewall" = "reconfig" ]; then clear;
rm /etc/f-iptables/*1.cfg; $0;
echo; echo "   Updating default configurations: /etc/f-iptables/files1.cfg in $fprogram version $fver "; echo; echo; exit
elif [ "$mifirewall" = "eraserules" ]; then echo -n;
$ruta/iptables-nft -t filter -F ; $ruta/ip6tables-nft -t filter  -F ; $ruta/iptables-legacy -t filter -F ; $ruta/ip6tables-legacy -t filter -F ;
echo; echo; echo " Deleting all rules from ipv4 and ipv6 from iptables"; echo; echo; exit
############################       english: system script, the list option
############################       spanish: script de sistema, la opcion lista
elif [ "$mifirewall" = "list" ]; then echo -n
$brillo  ; echo "  ##########################   Fran iptables for legacy/netfilter filter firewall Linux TO ipv4 and BLOCKING ipv6"
$normal
$comprueba echo "  ##########################   The iptables-legacy:"
$comprueba $ruta/iptables-legacy -v -L INPUT
$comprueba $ruta/iptables-legacy -v -L OUTPUT
$comprueba echo "  ##########################   The iptables-nft:"
$comprueba $ruta/iptables-nft -v -L INPUT
$comprueba $ruta/iptables-nft -v -L OUTPUT
exit
############################       english: the longhelp option
############################       spanish: la opcion de larga ayuda
elif [ "$mifirewall" = "longhelp" ]; then echo; echo; $normal
echo "  the $fprogram version $fver "
echo "  #############################################"
echo
echo "  ######################    The iptables help: "
echo ""
echo "  The First Option  (To configure iptables):  reconfig or offline or client or server or allpermisive or eraserules"
echo "  The First Option        (To show sockets):  list or iproute or sockets or longhelp"
echo "  The Second option              (Optional):  configs in folder /etc/f-iptables/ : " $(ls /etc/f-iptables/)
echo "  For Example"
echo "                              (Example 1):  launch:  $0 list                 /to list iptables rules"
echo "                              (Example 2):  launch:  $0 client web1.cfg      /to config iptables like client web"
echo "                              (Example 3):  launch:  $0 lonhelp              /to show long help from $fprogram"
echo ""
echo "  Notes: $program version $fver  Wich only works with the ports selected in ipv4 in the config file choosed, blocking ipv6"
echo; echo;
echo "  ######################    The first option:"
echo ""
echo "     reconfig: to rewrite the default configs, files1.cfg"
echo "      offline: firewall to disconected for all servers and clients"
echo "       client: configure the firewall to be a internet client"
echo "       server: configure the firewall to be a internet client and internet server"
echo " allpermisive: firewall very very permisive"
echo "   eraserules: delete the iptables rules in ipv4 and ipv6"
echo "         list: list iptables rules"
echo "      iproute: show ip route tables"
echo "      sockets: show netsockets"
echo "     longhelp: this help"
echo ""
echo "  #####################     The second option: (optional):"
echo ""
echo "    when you launch $0 with client or server, it takes for default  /etc/f-iptables/default1.cfg"
echo "    default1.cfg has all variables para configure that you need to launch the client or the server"
echo "    with somes variables can be sufficent to create a new file cfg to client or to server"
echo ""
echo "  #####################     Examples:"
echo ""
echo " $0 client games1.cfg  :  firewall to allow connecto to web and games"
echo " $0 server server1.cfg :  firewall to server somes services"
echo " $0 eraserules         :  remove the iptables rules"
echo " $0 list               :  list iptables rules"
echo " $0 longhelp           :  show this help"
echo ""
echo "  #####################     Examples of variables to the configs files:"
echo "" ; cat $0 | head -55 | grep -iv ^# | tail -11 | grep -iv export
echo ""
echo "  #####################     license:"
echo ""
echo "  Download the latest version $fprogram from sourceforge: $web"
echo "  This script is free software with copyleft from licence gpl, it is free, with no warranty"
echo ""
exit
############################       english: The default option, the help option
############################	   spanish: La opcion por defecto, la opcion de ayuda
else echo; $brillo
echo "  The $fprogram version $fver"
echo "  ###########################################"
echo
echo "  ####################### The iptables help: "
echo ""
echo "  The First Option  (To configure iptables):  reconfig or offline or client or server or allpermisive or eraserules"
echo "  The First Option        (To show sockets):  list or iproute or sockets or longhelp"
echo "  The Second option              (Optional):  configs in folder /etc/f-iptables/ : " $(ls /etc/f-iptables/)
echo "  For Example"
echo "                              (Example 1):  launch:  $0 list                 /to list iptables rules"
echo "                              (Example 2):  launch:  $0 client web1.cfg      /to config iptables like client web"
echo "                              (Example 3):  launch:  $0 lonhelp              /to show long help from $fprogram"
echo ""
echo "  Notes: $fprogram version $fver  Wich only works with the ports selected in ipv4 in the config file choosed, blocking ipv6"
echo; $normal; exit 0; fi
###########################        english: script information to when actived
###########################        spanish: informacion del script cuando se activa
echo
echo configuring iptables variables
echo variables actives
echo
############################       english: iptables rules
############################       spanish: reglas de iptables
echo Config iptables-legacy
 $ruta/iptables-legacy -t filter -F
 $ruta/iptables-legacy -t nat -F
 $ruta/iptables-legacy -t mangle -F
 $ruta/ip6tables-legacy -t filter -F
 $ruta/ip6tables-legacy -t nat -F
 $ruta/ip6tables-legacy -t mangle -F
 $ruta/ip6tables-legacy -A INPUT -j DROP
 $ruta/ip6tables-legacy -A OUTPUT -j DROP
 $ruta/ip6tables-legacy -A FORWARD -j DROP
 $ruta/iptables-legacy -A INPUT  -s 127.0.0.1 -d 127.0.0.1  -j ACCEPT > /dev/null
$haylogserver  $ruta/iptables-legacy -A INPUT -p tcp -m multiport --dports $logservertcp -j LOG > /dev/null
$hayvpn  $ruta/iptables-legacy -A INPUT -s $vpn -j ACCEPT > /dev/null
$activarservidor  $ruta/iptables-legacy -A INPUT -p udp -m multiport --dports $servidorudp -s $redserver -d $redserver -j ACCEPT > /dev/null
$activarservidor  $ruta/iptables-legacy -A INPUT -p tcp -m multiport --dports $servidortcp -s $redserver -d $redserver -j ACCEPT > /dev/null
$activarcliente  $ruta/iptables-legacy -A INPUT -p udp -m multiport --sports $clienteudp -m state --state established -s $redcliente -d $redcliente -j ACCEPT > /dev/null
$activarcliente  $ruta/iptables-legacy -A INPUT -p tcp -m multiport --sports $clientetcp -m state --state established -s $redcliente -d $redcliente -j ACCEPT > /dev/null
$hayping  $ruta/iptables-legacy -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT > /dev/null
 $ruta/iptables-legacy -A INPUT -j DROP > /dev/null
 $ruta/iptables-legacy -A OUTPUT -s 127.0.0.1 -d 127.0.0.1 -j ACCEPT > /dev/null
$hayvpn  $ruta/iptables-legacy -A OUTPUT -d $vpn -j ACCEPT > /dev/null
$activarservidor  $ruta/iptables-legacy -A OUTPUT -p udp -m multiport --sports $servidorudp -s $redserver -d $redserver -j ACCEPT > /dev/null
$activarservidor  $ruta/iptables-legacy -A OUTPUT -p tcp -m multiport --sports $servidortcp -s $redserver -d $redserver -j ACCEPT > /dev/null
$activarcliente   $ruta/iptables-legacy -A OUTPUT -p udp -m multiport --dports $clienteudp -s $redcliente -d $redcliente -j ACCEPT > /dev/null
$activarcliente  $ruta/iptables-legacy -A OUTPUT -p tcp -m multiport --dports $clientetcp -s $redcliente -d $redcliente -j ACCEPT > /dev/null
$hayping  $ruta/iptables-legacy -A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT > /dev/null
 $ruta/iptables-legacy -A OUTPUT -j DROP
 $ruta/iptables-legacy -A FORWARD  -j DROP
echo iptables-legacy active
echo
echo Config iptables-nft
 $ruta/iptables-nft -t filter -F
 $ruta/iptables-nft -t nat -F
 $ruta/iptables-nft -t mangle -F
 $ruta/ip6tables-nft -t filter -F
 $ruta/ip6tables-nft -t nat -F
 $ruta/ip6tables-nft -t mangle -F
 $ruta/ip6tables-nft -A INPUT -j DROP
 $ruta/ip6tables-nft -A OUTPUT -j DROP
 $ruta/ip6tables-nft -A FORWARD -j DROP
 $ruta/iptables-nft -A INPUT -s 127.0.0.1 -d 127.0.0.1  -j ACCEPT > /dev/null
$haylogserver  $ruta/iptables-nft -A INPUT -p tcp -m multiport --dports $logservertcp -j LOG > /dev/null
$hayvpn  $ruta/iptables-nft -A INPUT -s $vpn -j ACCEPT > /dev/null
$activarservidor  $ruta/iptables-nft -A INPUT -p udp -m multiport --dports $servidorudp -s $redserver -d $redserver -j ACCEPT > /dev/null
$activarservidor  $ruta/iptables-nft -A INPUT -p tcp -m multiport --dports $servidortcp -s $redserver -d $redserver -j ACCEPT > /dev/null
$activarcliente  $ruta/iptables-nft -A INPUT -p udp -m multiport --sports $clienteudp -m state --state established -s $redcliente -d $redcliente -j ACCEPT > /dev/null
$activarcliente  $ruta/iptables-nft -A INPUT -p tcp -m multiport --sports $clientetcp -m state --state established -s $redcliente -d $redcliente -j ACCEPT > /dev/null
$hayping  $ruta/iptables-nft -A INPUT -p icmp --icmp-type echo-reply  -j ACCEPT > /dev/null
 $ruta/iptables-nft -A INPUT -j DROP > /dev/null
 $ruta/iptables-nft -A OUTPUT -s 127.0.0.1 -d 127.0.0.1 -j ACCEPT > /dev/null
$hayvpn  $ruta/iptables-nft -A OUTPUT -d $vpn -j ACCEPT > /dev/null
$activarservidor  $ruta/iptables-nft -A OUTPUT -p udp -m multiport --sports $servidorudp -s $redserver -d $redserver -j ACCEPT > /dev/null
$activarservidor  $ruta/iptables-nft -A OUTPUT -p tcp -m multiport --sports $servidortcp -s $redserver -d $redserver -j ACCEPT > /dev/null
$activarcliente  $ruta/iptables-nft -A OUTPUT -p udp -m multiport --dports $clienteudp -s $redcliente -d $redcliente -j ACCEPT > /dev/null
$activarcliente  $ruta/iptables-nft -A OUTPUT -p tcp -m multiport --dports $clientetcp -s $redcliente -d $redcliente -j ACCEPT > /dev/null
$hayping  $ruta/iptables-nft -A OUTPUT -p icmp --icmp-type echo-request  -j ACCEPT > /dev/null
 $ruta/iptables-nft -A OUTPUT -j DROP
 $ruta/iptables-nft -A FORWARD -j DROP
echo iptables-nft active
echo
$mojado  $ruta/iptables-legacy -F > /dev/null
$mojado  $ruta/iptables-legacy -A INPUT  -s 127.0.0.1 -d 127.0.0.1  -j ACCEPT > /dev/null
$mojado  $ruta/iptables-legacy -A INPUT -m state --state established -j ACCEPT > /dev/null
$mojado  $ruta/iptables-legacy -A INPUT -j DROP > /dev/null
$mojado  $ruta/iptables-legacy -A OUTPUT -j ACCEPT > /dev/null
$mojado  $ruta/iptables-legacy -A FORWARD  -j DROP > /dev/null
$mojado  $ruta/iptables-nft -F > /dev/null
$mojado  $ruta/iptables-nft -A INPUT -s 127.0.0.1 -d 127.0.0.1  -j ACCEPT > /dev/null
$mojado  $ruta/iptables-nft -A INPUT -m state --state established -j ACCEPT > /dev/null
$mojado  $ruta/iptables-nft -A INPUT -j DROP > /dev/null
$mojado  $ruta/iptables-nft -A OUTPUT -j ACCEPT > /dev/null
$mojado  $ruta/iptables-nft -A FORWARD -j DROP > /dev/null
#########################       english: when active rules
#########################       spanish: cuando activas las reglas
echo launched $0 $1
if [ -f /etc/f-iptables/$2 ]; then echo with the configuration: $2 ;
else echo with the configuration: default1.cfg; fi ;
$brillo
echo ;
echo client tcp: $clientetcp ;
echo client udp: $clienteudp ;
if [ "$1" = "server" ]; then echo -n ;
echo ;
echo server tcp: $servidortcp ;
echo server udp: $servidorudp ;
else echo -n ; fi ;
echo ;
echo $fprogram version $fver ;
echo ;
$normal
# left script
#######################         english: End of script
#######################         spanish: fin del script
exit 0
