#!/bin/bash
####
#### File:        myradio-bash
#### Description: Command Fran Radio Selector From Internet Link
#### Author:      Francisco Garcia <fwiptables@gmx.com>
#### Copyright:   (c) 2020-2024 Francisco Garcia <fwiptables@gmx.com>
####
#### This program is free software; you can redistribute it and/or modify
#### it under the terms of the GNU General Public License as published by
#### the Free Software Foundation; either version 2 of the License, or
#### (at your option) any later version.
####
#### This program is distributed in the hope that it will be useful,
#### but WITHOUT ANY WARRANTY; without even the implied warranty of
#### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#### GNU General Public License for more details.
####
#### You should have received a copy of the GNU General Public License along
#### with this program; if not, write to the Free Software Foundation, Inc.,
#### 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
####
##################################################### non root
if [ "$(id -u)" == "0" ]; then echo "# launch as user, not root allowed"; exit; fi
##################################################### configuration list
### variables principal list
opt_name="myradio-bash"
opt_version="24-11-J"
opt_realpath="$(realpath $0)"
opt_basename="$(basename $0)"
opt_first="$1"
opt_second="$2"
### variables secondary list
conf_agent="curl"          # the preferences
conf_player="vlc -I dummy" # the preferences
conf_kill="vlc"            # the preferences
conf_proxy=""              # the preferences
conf_musica="$HOME/musica" # the preferences
conf_radio="https://www.tdtchannels.com/lists/radio.m3u8" # the preferences
conf_folder="$HOME/.config/myradio-bash"                  # the preferences
conf_complete="$conf_folder/myradio-list.m3u8"            # the preferences
conf_choosed="$conf_folder/myradio-choosed.m3u8"          # the preferences
conf_config="$conf_folder/myradio-config.txt"             # the preferences
###
##################################################### update config
if [ ! -d "$conf_folder" ]; then mkdir -p $conf_folder ; fi
if [ ! -f "$conf_config" ]; then 
cat $0 | grep "the preferences" | grep -iv conf_config > $conf_config
echo "# config created $conf_config"  ; fi
if [ ! -f "$conf_complete" ]; then  $opt_realpath update ; fi
### load config
source $conf_config
###
##################################################### options list
### reset config
if [ "$opt_first" == "reset" ]; then
cat $0 | grep "the preferences" | grep -iv conf_config > $conf_config
echo "# config created $conf_config"
exit ; fi
### config file
if [ "$opt_first" == "config" ]; then
cat $conf_config
echo "# you can edit config file: $conf_config"
exit ; fi
### update list
if [ "$opt_first" == "update" ]; then
$conf_agent $conf_radio -L -s -o $conf_complete
echo "# $conf_radio donloaded"
exit; fi
### stop music
if [ "$opt_first" == "stop" ] ; then
killall -9 $conf_kill &> /dev/null
exit; fi
### search radio
if [ "$opt_first" == "search" ]; then
echo "# searching radio: $opt_second"
grep -i $2 $conf_complete
exit; fi
### busca musica
if [ "$opt_first" == "busca" ]; then
echo "# searching musica: $opt_second"
ls -1 $conf_musica | grep -i $2
exit; fi
### play musica
if [ "$opt_first" == "musica" ]; then
$opt_realpath stop
if [ "$opt_second" == "$NULL" ];
then echo "# play musica: $conf_musica"
$conf_player -d $conf_musica &> /dev/null
else for a in "$(ls -1 $conf_musica | grep -i $opt_second)"
do echo $a ; $conf_player $conf_musica/$a &> /dev/null ; done ; fi
exit; fi
### play radio
if [ "$opt_first" == "radio" ]; then
if [ "$opt_second" == "$NULL" ]; then echo "# choose a name for one radio"; exit; fi
$opt_realpath stop
grep -i $opt_second $conf_complete > $conf_choosed
if [ ! -s "$conf_choosed" ]; then echo "# radio not found" ; exit; fi
if [ "$conf_proxy" == "$NULL" ]
then $conf_player -d $conf_choosed &> /dev/null
else $conf_player --socks $conf_proxy -d $conf_choosed &> /dev/null
fi
echo "# now playing radio: $opt_second"
exit; fi
### link radio
if [ "$opt_first" == "link" ]; then
$opt_realpath stop
echo "# playing: $opt_second" ;
$conf_player -d $opt_second
exit; fi
### code program
if [ "$opt_first" == "code" ]; then
echo "# source code script"
cat $opt_realpath
exit; fi
### about
if [ "$opt_first" == "about" ]; then
echo "# about"
echo "#### File:        myradio-bash"
echo "#### Description: Command Fran Radio Selector From Internet Link"
echo "#### Author:      Francisco Garcia <fwiptables@gmx.com>"
echo "#### Copyright:   (c) 2020-2024 Francisco Garcia <fwiptables@gmx.com>"
echo
echo "$opt_name $opt_version"
exit; fi
### about
if [ "$opt_first" == "help" ]; then
echo "# Option:  info"
echo "# -------  ----"
echo "# info:    this help"
echo "# about:   license and version"
echo "# config:  show the actual user config for myradio-bash"
echo "# reset:   reset the user config for my radio-bash"
echo "# stop:    stop the player"
echo "# update:  update the file m3u8 to play radio"
echo "# search:  search in the file m3u8 to play radio"
echo "# busca:   search in the musica folder" 
echo "# radio:   play one radio with pattern"
echo "# musica:  play folder music in $conf_musica"
echo "# link:    choose una web link to play"
exit; fi
### invalid options
echo "# option no valid # choose one option to launch"
echo "# $opt_basename help|about|reset|config|stop|\
update|search|busca|radio|musica|link [music]"
##################################################### exit options
exit


